service: BrdToStudio

provider:
  name: aws
  runtime: nodejs6.10

functions:
  exportToStudio:
    handler: exportToStudio.exportToStudio
    events:
      - http:
          path: /exportToStudio
          method: post

plugins:
  - serverless-offline

