service: BrdToStudio

provider:
  name: aws
  runtime: nodejs6.10

functions:
  exportToStudio:
    handler: exportToStudio.exportCallFlow
    events:
      - http:
          path: /exportCallFlow
          method: post

plugins:
  - serverless-offline

